//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySql.Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySql.Utility.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding or editing connections is not allowed when MySQL Workbench is running..
        /// </summary>
        internal static string AddOrEditConnectionsNotAllowed {
            get {
                return ResourceManager.GetString("AddOrEditConnectionsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///Thrown by: {1}.{2}.
        /// </summary>
        internal static string ApplicationExceptionForLog {
            get {
                return ResourceManager.GetString("ApplicationExceptionForLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception message:
        ///{2}
        ///
        ///Exception thrown by:
        ///{0}.{1}
        ///
        ///Stack trace:
        ///{3}.
        /// </summary>
        internal static string ApplicationExceptionForMoreInfo {
            get {
                return ResourceManager.GetString("ApplicationExceptionForMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Exception.
        /// </summary>
        internal static string ApplicationExceptionText {
            get {
                return ResourceManager.GetString("ApplicationExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///Thrown by: {1}.{2}
        ///Exception message: {3}.
        /// </summary>
        internal static string ApplicationExceptionWithCustomMessageForLog {
            get {
                return ResourceManager.GetString("ApplicationExceptionWithCustomMessageForLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \MySQL\MySQL Installer.
        /// </summary>
        internal static string BaseInstallerPath {
            get {
                return ResourceManager.GetString("BaseInstallerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButtonDefaultText {
            get {
                return ResourceManager.GetString("CancelButtonDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to create or edit connections, please close MySQL Workbench..
        /// </summary>
        internal static string CloseWBAdviceToAddOrEditConnections {
            get {
                return ResourceManager.GetString("CloseWBAdviceToAddOrEditConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to remove a connection, please close MySQL Workbench..
        /// </summary>
        internal static string CloseWBAdviceToDelete {
            get {
                return ResourceManager.GetString("CloseWBAdviceToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\ProgramData\MySQL\MySQL Installer for Windows\settings-Commercial.xml.
        /// </summary>
        internal static string CommercialXMLFilePath {
            get {
                return ResourceManager.GetString("CommercialXMLFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\ProgramData\MySQL\MySQL Installer for Windows\settings-Community.xml.
        /// </summary>
        internal static string CommunityXMLFilePath {
            get {
                return ResourceManager.GetString("CommunityXMLFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection attempt failed..
        /// </summary>
        internal static string ConnectFailedWarningTitle {
            get {
                return ResourceManager.GetString("ConnectFailedWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection with the name &quot;{0}&quot; exists already. Please choose another name..
        /// </summary>
        internal static string ConnectionAlreadyExistsError {
            get {
                return ResourceManager.GetString("ConnectionAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to MySQL Server instance at {0} with user {1} and no password..
        /// </summary>
        internal static string ConnectionErrorDetailNoPassword {
            get {
                return ResourceManager.GetString("ConnectionErrorDetailNoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to MySQL Server instance at {0} with user {1} and the given password..
        /// </summary>
        internal static string ConnectionErrorDetailWithPassword {
            get {
                return ResourceManager.GetString("ConnectionErrorDetailWithPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        internal static string ConnectionErrorTitle {
            get {
                return ResourceManager.GetString("ConnectionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MySQL server is using SSL and requires a secure connection, but the client connection has SSL turned off..
        /// </summary>
        internal static string ConnectionInsecureError {
            get {
                return ResourceManager.GetString("ConnectionInsecureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This connection is not set to use SSL, but the MySQL server requires a secure connection..
        /// </summary>
        internal static string ConnectionIsInsecureAndRequiresRsaKeyRetrievalDetail {
            get {
                return ResourceManager.GetString("ConnectionIsInsecureAndRequiresRsaKeyRetrievalDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieval of the RSA public key is not enabled for insecure connections.
        /// </summary>
        internal static string ConnectionIsInsecureAndRequiresRsaKeyRetrievalError {
            get {
                return ResourceManager.GetString("ConnectionIsInsecureAndRequiresRsaKeyRetrievalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MySQL server is using SSL and it requires a secure connection from the client.
        ///This connection is explicitly turning off the use of SSL (Use SSL = No).
        ///
        ///It is advised that the connection is set to use the &quot;Preferred&quot; or &quot;Required&quot; SSL mode in order to connect to this server.
        ///
        ///If, for some reason, using SSL is not an option, the password can still be sent to the server after encrypting it with a RSA key. The client can request the public key from the server, however this could be prone to man-in-the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConnectionIsInsecureAndRequiresRsaKeyRetrievalMoreInfo {
            get {
                return ResourceManager.GetString("ConnectionIsInsecureAndRequiresRsaKeyRetrievalMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you trust the server to send an RSA key to encrypt the password?.
        /// </summary>
        internal static string ConnectionIsInsecureAndRequiresRsaKeyRetrievalSubDetail {
            get {
                return ResourceManager.GetString("ConnectionIsInsecureAndRequiresRsaKeyRetrievalSubDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MySQL server requires a secure connection.
        /// </summary>
        internal static string ConnectionIsInsecureAndRequiresRsaKeyRetrievalTitle {
            get {
                return ResourceManager.GetString("ConnectionIsInsecureAndRequiresRsaKeyRetrievalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection name is required and cannot be empty..
        /// </summary>
        internal static string ConnectionNameRequiredError {
            get {
                return ResourceManager.GetString("ConnectionNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password for the connection:.
        /// </summary>
        internal static string ConnectionPasswordLabelText {
            get {
                return ResourceManager.GetString("ConnectionPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection passwords were migrated successfully..
        /// </summary>
        internal static string ConnectionPasswordsMigratedText {
            get {
                return ResourceManager.GetString("ConnectionPasswordsMigratedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error was thrown when trying to migrate connection passwords:.
        /// </summary>
        internal static string ConnectionPasswordsNotMigratedText {
            get {
                return ResourceManager.GetString("ConnectionPasswordsNotMigratedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Password.
        /// </summary>
        internal static string ConnectionPasswordWindowTitleText {
            get {
                return ResourceManager.GetString("ConnectionPasswordWindowTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when loading database connections file.
        /// </summary>
        internal static string ConnectionsFileLoadingErrorTitle {
            get {
                return ResourceManager.GetString("ConnectionsFileLoadingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save database connections file.
        /// </summary>
        internal static string ConnectionsFileSavingErrorTitle {
            get {
                return ResourceManager.GetString("ConnectionsFileSavingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} database connections were processed for migration..
        /// </summary>
        internal static string ConnectionsMigratedDetail {
            get {
                return ResourceManager.GetString("ConnectionsMigratedDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following {0} connections were renamed before migrating them since Workbench connections already existed with those names:.
        /// </summary>
        internal static string ConnectionsMigratedRenamedMoreInfo {
            get {
                return ResourceManager.GetString("ConnectionsMigratedRenamedMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following {0} connections were migrated to the MySQL Workbench connections file:.
        /// </summary>
        internal static string ConnectionsMigratedSuccessfullyMoreInfo {
            get {
                return ResourceManager.GetString("ConnectionsMigratedSuccessfullyMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already migrated.
        /// </summary>
        internal static string ConnectionsMigrationAlreadyText {
            get {
                return ResourceManager.GetString("ConnectionsMigrationAlreadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local database connections could not be migrated..
        /// </summary>
        internal static string ConnectionsMigrationErrorDetail {
            get {
                return ResourceManager.GetString("ConnectionsMigrationErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connections were not migrated because the following error ocurred:.
        /// </summary>
        internal static string ConnectionsMigrationErrorMoreInfo {
            get {
                return ResourceManager.GetString("ConnectionsMigrationErrorMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating connections..
        /// </summary>
        internal static string ConnectionsMigrationErrorTitle {
            get {
                return ResourceManager.GetString("ConnectionsMigrationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indefinite, migrate manually.
        /// </summary>
        internal static string ConnectionsMigrationIndefiniteText {
            get {
                return ResourceManager.GetString("ConnectionsMigrationIndefiniteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No migration needed.
        /// </summary>
        internal static string ConnectionsMigrationNotNeededText {
            get {
                return ResourceManager.GetString("ConnectionsMigrationNotNeededText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections and passwords migrated successfully..
        /// </summary>
        internal static string ConnectionsMigrationSuccessTitle {
            get {
                return ResourceManager.GetString("ConnectionsMigrationSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections migrated successfully, but not passwords..
        /// </summary>
        internal static string ConnectionsMigrationWarningTitle {
            get {
                return ResourceManager.GetString("ConnectionsMigrationWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following {0} connections were not migrated since identical connections already existed in the Workbench connections file:.
        /// </summary>
        internal static string ConnectionsNotMigratedMoreInfo {
            get {
                return ResourceManager.GetString("ConnectionsNotMigratedMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refusing Connections.
        /// </summary>
        internal static string ConnectionStatusBad {
            get {
                return ResourceManager.GetString("ConnectionStatusBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepting Connections.
        /// </summary>
        internal static string ConnectionStatusGood {
            get {
                return ResourceManager.GetString("ConnectionStatusGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string ConnectionStatusNA {
            get {
                return ResourceManager.GetString("ConnectionStatusNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySql Server connection to {0} with user {1} was successful..
        /// </summary>
        internal static string ConnectionSuccessDetail {
            get {
                return ResourceManager.GetString("ConnectionSuccessDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Success.
        /// </summary>
        internal static string ConnectionSuccessTitle {
            get {
                return ResourceManager.GetString("ConnectionSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A possible fail reason could be that your user requires a SSL connection that is not currently supported.
        ///
        ///Please check with the Administrator if you require a SSL Connection and if he can authorize your user to login without a SSL connection..
        /// </summary>
        internal static string ConnectSSLFailedDetailWarning {
            get {
                return ResourceManager.GetString("ConnectSSLFailedDetailWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete {0}&apos;s database connections file..
        /// </summary>
        internal static string ConsumerApplicationConnectionsFileDeleteErrorDetail {
            get {
                return ResourceManager.GetString("ConsumerApplicationConnectionsFileDeleteErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete {0}&apos;s passwords vault file..
        /// </summary>
        internal static string ConsumerApplicationPasswordsFileDeleteErrorDetail {
            get {
                return ResourceManager.GetString("ConsumerApplicationPasswordsFileDeleteErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Core.dll.
        /// </summary>
        internal static string CoreDllFileExtension {
            get {
                return ResourceManager.GetString("CoreDllFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of coordinates must be greater than 1 to define a Curve..
        /// </summary>
        internal static string CurveInvalidNumberOfCoordinatesError {
            get {
                return ResourceManager.GetString("CurveInvalidNumberOfCoordinatesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default schema, leave blank to select it later..
        /// </summary>
        internal static string DefaultSchemaNotRequiredHelpText {
            get {
                return ResourceManager.GetString("DefaultSchemaNotRequiredHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A default schema is required..
        /// </summary>
        internal static string DefaultSchemaRequiredError {
            get {
                return ResourceManager.GetString("DefaultSchemaRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default schema, this field is required..
        /// </summary>
        internal static string DefaultSchemaRequiredHelpText {
            get {
                return ResourceManager.GetString("DefaultSchemaRequiredHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .exe.
        /// </summary>
        internal static string ExeFileExtension {
            get {
                return ResourceManager.GetString("ExeFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password for the MySQL account has expired.
        ///Please enter a new password:.
        /// </summary>
        internal static string ExpiredPasswordLabelText {
            get {
                return ResourceManager.GetString("ExpiredPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Expired.
        /// </summary>
        internal static string ExpiredPasswordWindowTitleText {
            get {
                return ResourceManager.GetString("ExpiredPasswordWindowTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot fetch the X Protocol port from the server {0}..
        /// </summary>
        internal static string FetchXProtocolError {
            get {
                return ResourceManager.GetString("FetchXProtocolError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist..
        /// </summary>
        internal static string FileDoesNotExistError {
            get {
                return ResourceManager.GetString("FileDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is required..
        /// </summary>
        internal static string FileRequiredError {
            get {
                return ResourceManager.GetString("FileRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button1.
        /// </summary>
        internal static string GenericButton1DefaultText {
            get {
                return ResourceManager.GetString("GenericButton1DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button2.
        /// </summary>
        internal static string GenericButton2DefaultText {
            get {
                return ResourceManager.GetString("GenericButton2DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button3.
        /// </summary>
        internal static string GenericButton3DefaultText {
            get {
                return ResourceManager.GetString("GenericButton3DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Ocurred.
        /// </summary>
        internal static string GenericErrorTitle {
            get {
                return ResourceManager.GetString("GenericErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL Error {0}:{1}.
        /// </summary>
        internal static string GenericMySQLError {
            get {
                return ResourceManager.GetString("GenericMySQLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexadecimal string has an invalid length..
        /// </summary>
        internal static string HexToBytesValueLengthError {
            get {
                return ResourceManager.GetString("HexToBytesValueLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide {0}.
        /// </summary>
        internal static string HidePrefixText {
            get {
                return ResourceManager.GetString("HidePrefixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Severity Error.
        /// </summary>
        internal static string HighSeverityError {
            get {
                return ResourceManager.GetString("HighSeverityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a parent form to attach the dialog to..
        /// </summary>
        internal static string InfoDialogNoParentError {
            get {
                return ResourceManager.GetString("InfoDialogNoParentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string InformationText {
            get {
                return ResourceManager.GetString("InformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance has been already disposed..
        /// </summary>
        internal static string InstanceAlreadyDisposedError {
            get {
                return ResourceManager.GetString("InstanceAlreadyDisposedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid geometry type encountered in {0}..
        /// </summary>
        internal static string InvalidGeometryParsedError {
            get {
                return ResourceManager.GetString("InvalidGeometryParsedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid geometry type encountered in {0}..
        /// </summary>
        internal static string InvalidGeometryTypeError {
            get {
                return ResourceManager.GetString("InvalidGeometryTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL PEM file does not exist or is invalid..
        /// </summary>
        internal static string InvalidPemFileDetail {
            get {
                return ResourceManager.GetString("InvalidPemFileDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SSL PEM file.
        /// </summary>
        internal static string InvalidPemFileTitle {
            get {
                return ResourceManager.GetString("InvalidPemFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key file does not exist or is invalid..
        /// </summary>
        internal static string InvalidPrivateKeyFileDetail {
            get {
                return ResourceManager.GetString("InvalidPrivateKeyFileDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid private key file.
        /// </summary>
        internal static string InvalidPrivateKeyFileTitle {
            get {
                return ResourceManager.GetString("InvalidPrivateKeyFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WexInstaller.
        /// </summary>
        internal static string LegacyInstallerFilename {
            get {
                return ResourceManager.GetString("LegacyInstallerFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Logger properties that define a log file path and name have not been set..
        /// </summary>
        internal static string LogFileNotDefinedError {
            get {
                return ResourceManager.GetString("LogFileNotDefinedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file {0} does not exist.
        /// </summary>
        internal static string LogFileNotExistsErrorText {
            get {
                return ResourceManager.GetString("LogFileNotExistsErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections will be migrated to use MySQL Workbench&apos;s connections file..
        /// </summary>
        internal static string MigrateConnectionsToWorkbenchInfoDetail {
            get {
                return ResourceManager.GetString("MigrateConnectionsToWorkbenchInfoDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} now works with the connections file used by MySQL Workbench if it is installed.
        ///
        ///{0} will attempt to merge all existing connections with MySQL Workbench and in order to do this MySQLWorkbench must not be running.
        ///
        ///Please make sure MySQL Workbench is closed to continue with the merging operation.
        ///If you choose not to migrate connections now, you will be prompted later to perform the migration..
        /// </summary>
        internal static string MigrateConnectionsToWorkbenchInfoMoreInfo {
            get {
                return ResourceManager.GetString("MigrateConnectionsToWorkbenchInfoMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to migrate connections now?.
        /// </summary>
        internal static string MigrateConnectionsToWorkbenchInfoSubDetail {
            get {
                return ResourceManager.GetString("MigrateConnectionsToWorkbenchInfoSubDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connections will be migrated.
        /// </summary>
        internal static string MigrateConnectionsToWorkbenchInfoTitle {
            get {
                return ResourceManager.GetString("MigrateConnectionsToWorkbenchInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string MoreInfoText {
            get {
                return ResourceManager.GetString("MoreInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find MySQL Installer..
        /// </summary>
        internal static string MySQLInstallerNotInstalled {
            get {
                return ResourceManager.GetString("MySQLInstallerNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot consist of only digits..
        /// </summary>
        internal static string MySqlSchemaTableNameAllDigitsError {
            get {
                return ResourceManager.GetString("MySqlSchemaTableNameAllDigitsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be empty or consist of only white space characters..
        /// </summary>
        internal static string MySqlSchemaTableNameEmptyOrWhiteSpaceError {
            get {
                return ResourceManager.GetString("MySqlSchemaTableNameEmptyOrWhiteSpaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot end with white space characters..
        /// </summary>
        internal static string MySqlSchemaTableNameEndsWithWhiteSpaceError {
            get {
                return ResourceManager.GetString("MySqlSchemaTableNameEndsWithWhiteSpaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot exceed the maximum allowed length of {0} characters..
        /// </summary>
        internal static string MySqlSchemaTableNameExceedsMaxLengthError {
            get {
                return ResourceManager.GetString("MySqlSchemaTableNameExceedsMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid cluster name..
        /// </summary>
        internal static string MySqlServerClusterNameInvalid {
            get {
                return ResourceManager.GetString("MySqlServerClusterNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster name must not exceed 40 characters..
        /// </summary>
        internal static string MySqlServerClusterNameMaxLengthExceeded {
            get {
                return ResourceManager.GetString("MySqlServerClusterNameMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster name is required..
        /// </summary>
        internal static string MySqlServerClusterNameRequired {
            get {
                return ResourceManager.GetString("MySqlServerClusterNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script executed successfully..
        /// </summary>
        internal static string MySqlServerInstanceInfoExecuteScriptExecutionSuccess {
            get {
                return ResourceManager.GetString("MySqlServerInstanceInfoExecuteScriptExecutionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to {0} at port {1}..
        /// </summary>
        internal static string MySqlServerInstanceInfoExecuteScriptsCannotConnectError {
            get {
                return ResourceManager.GetString("MySqlServerInstanceInfoExecuteScriptsCannotConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error ocurred attempting to execute script:{1}{0}{1}.
        /// </summary>
        internal static string MySqlServerInstanceInfoExecuteScriptsExecutionError {
            get {
                return ResourceManager.GetString("MySqlServerInstanceInfoExecuteScriptsExecutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing script:.
        /// </summary>
        internal static string MySqlServerInstanceInfoExecutingScript {
            get {
                return ResourceManager.GetString("MySqlServerInstanceInfoExecutingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The host name or IP address is not well formed..
        /// </summary>
        internal static string MySqlServerInstanceInvalidHostOrIpError {
            get {
                return ResourceManager.GetString("MySqlServerInstanceInvalidHostOrIpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name or IP address is required..
        /// </summary>
        internal static string MySqlServerInstanceRequiredHostOrIpError {
            get {
                return ResourceManager.GetString("MySqlServerInstanceRequiredHostOrIpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port number is outside valid range of {0} and {1}..
        /// </summary>
        internal static string MySqlServerInvalidPortRange {
            get {
                return ResourceManager.GetString("MySqlServerInvalidPortRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password does not meet the minimum length requirement of 4 characters..
        /// </summary>
        internal static string MySqlServerPasswordNotGoodEnough {
            get {
                return ResourceManager.GetString("MySqlServerPasswordNotGoodEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string MySqlServerPasswordRequired {
            get {
                return ResourceManager.GetString("MySqlServerPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified port is already in use..
        /// </summary>
        internal static string MySqlServerPortInUse {
            get {
                return ResourceManager.GetString("MySqlServerPortInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value is not valid..
        /// </summary>
        internal static string MySqlServerPortNumberInvalid {
            get {
                return ResourceManager.GetString("MySqlServerPortNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port number is required.
        /// </summary>
        internal static string MySqlServerPortNumberRequired {
            get {
                return ResourceManager.GetString("MySqlServerPortNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid user name..
        /// </summary>
        internal static string MySqlServerUsernameInvalid {
            get {
                return ResourceManager.GetString("MySqlServerUsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name &quot;root&quot; is reserved and cannot be used..
        /// </summary>
        internal static string MySqlServerUserNameInvalidRoot {
            get {
                return ResourceManager.GetString("MySqlServerUserNameInvalidRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name must not exceed 32 characters..
        /// </summary>
        internal static string MySqlServerUsernameMaxLengthExceeded {
            get {
                return ResourceManager.GetString("MySqlServerUsernameMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required..
        /// </summary>
        internal static string MySqlServerUsernameRequired {
            get {
                return ResourceManager.GetString("MySqlServerUsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required to establish a connection..
        /// </summary>
        internal static string MySqlUserNameRequiredError {
            get {
                return ResourceManager.GetString("MySqlUserNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQLInstaller.
        /// </summary>
        internal static string NewInstallerFilename {
            get {
                return ResourceManager.GetString("NewInstallerFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap no {
            get {
                object obj = ResourceManager.GetObject("no", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoButtonText {
            get {
                return ResourceManager.GetString("NoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkButtonDefaultText {
            get {
                return ResourceManager.GetString("OkButtonDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password:.
        /// </summary>
        internal static string OldPasswordLabelText {
            get {
                return ResourceManager.GetString("OldPasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key is encrypted but passphrase is empty..
        /// </summary>
        internal static string PassphraseIsMissingError {
            get {
                return ResourceManager.GetString("PassphraseIsMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string PasswordLabelText {
            get {
                return ResourceManager.GetString("PasswordLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error resetting password..
        /// </summary>
        internal static string PasswordResetErrorDetail {
            get {
                return ResourceManager.GetString("PasswordResetErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred trying to reset the password for the current user.
        ///Please select your MySQL connection again to retry..
        /// </summary>
        internal static string PasswordResetErrorDetailText {
            get {
                return ResourceManager.GetString("PasswordResetErrorDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Error.
        /// </summary>
        internal static string PasswordResetErrorTitleText {
            get {
                return ResourceManager.GetString("PasswordResetErrorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading password&apos;s vault file..
        /// </summary>
        internal static string PasswordsFileLoadError {
            get {
                return ResourceManager.GetString("PasswordsFileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving password&apos;s vault file..
        /// </summary>
        internal static string PasswordsFileSaveError {
            get {
                return ResourceManager.GetString("PasswordsFileSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and its confirmation do not match. Please enter them again and make sure they match..
        /// </summary>
        internal static string PasswordsMismatchErrorText {
            get {
                return ResourceManager.GetString("PasswordsMismatchErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given path contains a colon (&quot;:&quot;) that is not part of a volume identifier (for example, &quot;c:\&quot;)..
        /// </summary>
        internal static string PathContainsColonError {
            get {
                return ResourceManager.GetString("PathContainsColonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters found in the path, or the path is badly formed..
        /// </summary>
        internal static string PathContainsInvalidCharactersError {
            get {
                return ResourceManager.GetString("PathContainsInvalidCharactersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file name was specified in the given path..
        /// </summary>
        internal static string PathContainsNoFileError {
            get {
                return ResourceManager.GetString("PathContainsNoFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given file path is null..
        /// </summary>
        internal static string PathIsNullError {
            get {
                return ResourceManager.GetString("PathIsNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory in the given path does not exist..
        /// </summary>
        internal static string PathNonExistentDirectoryError {
            get {
                return ResourceManager.GetString("PathNonExistentDirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given path is not an absolute path..
        /// </summary>
        internal static string PathNotAbsoluteError {
            get {
                return ResourceManager.GetString("PathNotAbsoluteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute path exceeds the maximum length allowed for a path..
        /// </summary>
        internal static string PathTooLongError {
            get {
                return ResourceManager.GetString("PathTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given file path is invalid..
        /// </summary>
        internal static string PathUnknownError {
            get {
                return ResourceManager.GetString("PathUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} name cannot contain back slashes (&apos;\&apos;)..
        /// </summary>
        internal static string PipeOrSharedMemoryNameBackSlashesError {
            get {
                return ResourceManager.GetString("PipeOrSharedMemoryNameBackSlashesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entire {0} name string cannot be more than 256 characters long..
        /// </summary>
        internal static string PipeOrSharedMemoryNameLengthError {
            get {
                return ResourceManager.GetString("PipeOrSharedMemoryNameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} name is required, it cannot be null, empty or contain only white spaces..
        /// </summary>
        internal static string PipeOrSharedMemoryNameRequiredError {
            get {
                return ResourceManager.GetString("PipeOrSharedMemoryNameRequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press {0} to continue..
        /// </summary>
        internal static string PressButtonText {
            get {
                return ResourceManager.GetString("PressButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring thread is already running..
        /// </summary>
        internal static string RegistryMonitorAlreadyRunningError {
            get {
                return ResourceManager.GetString("RegistryMonitorAlreadyRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registry hive &apos;{0}&apos; is not valid or recognized..
        /// </summary>
        internal static string RegistryMonitorInvalidHiveError {
            get {
                return ResourceManager.GetString("RegistryMonitorInvalidHiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load repository XML file..
        /// </summary>
        internal static string RepositoryFileLoadingErrorDetail {
            get {
                return ResourceManager.GetString("RepositoryFileLoadingErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The repository XML file could not be loaded and it may be corrupt..
        /// </summary>
        internal static string RepositoryFileRecreateDetail {
            get {
                return ResourceManager.GetString("RepositoryFileRecreateDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to re-create the XML file from scratch?.
        /// </summary>
        internal static string RepositoryFileRecreateSubDetail {
            get {
                return ResourceManager.GetString("RepositoryFileRecreateSubDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreate file.
        /// </summary>
        internal static string RepositoryFileRecreateTitle {
            get {
                return ResourceManager.GetString("RepositoryFileRecreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to re-create repository XML file..
        /// </summary>
        internal static string RepositoryFileRecreatingErrorDetail {
            get {
                return ResourceManager.GetString("RepositoryFileRecreatingErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can retry the loading of the XML file (up to {0} time{1}).
        ///If you choose not to retry or the number of retries hits the limit, you will be given the option to attempt to re-create the XML file from scratch, since it may be corrupt.
        ///
        ///Error message:
        ///{2}.
        /// </summary>
        internal static string RepositoryFileRetryMoreInfo {
            get {
                return ResourceManager.GetString("RepositoryFileRetryMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to retry loading the file?.
        /// </summary>
        internal static string RepositoryFileRetrySubDetail {
            get {
                return ResourceManager.GetString("RepositoryFileRetrySubDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry?.
        /// </summary>
        internal static string RepositoryFileRetryTitle {
            get {
                return ResourceManager.GetString("RepositoryFileRetryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save repository XML file..
        /// </summary>
        internal static string RepositoryFileSavingErrorDetail {
            get {
                return ResourceManager.GetString("RepositoryFileSavingErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SakilaLogo {
            get {
                object obj = ResourceManager.GetObject("SakilaLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default schema can&apos;t be validated because a connection to MySQL Server instance at {0} could not be established..
        /// </summary>
        internal static string SchemaValidationFailConnectionFailure {
            get {
                return ResourceManager.GetString("SchemaValidationFailConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default schema can&apos;t be validated because the connected MySQL Server does not contain any schemas or schema information could not be retrieved..
        /// </summary>
        internal static string SchemaValidationFailNoSchemas {
            get {
                return ResourceManager.GetString("SchemaValidationFailNoSchemas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema ´{0}´ does not exist in the connected MySQL Server..
        /// </summary>
        internal static string SchemaValidationFailSchemaNotFound {
            get {
                return ResourceManager.GetString("SchemaValidationFailSchemaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred trying to flush the binary log..
        /// </summary>
        internal static string ServerInstanceBinaryLogFlushedError {
            get {
                return ResourceManager.GetString("ServerInstanceBinaryLogFlushedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary log flushed and master reset successfully..
        /// </summary>
        internal static string ServerInstanceBinaryLogFlushedSuccess {
            get {
                return ResourceManager.GetString("ServerInstanceBinaryLogFlushedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flushing binary log and resetting master....
        /// </summary>
        internal static string ServerInstanceFlushingBinaryLog {
            get {
                return ResourceManager.GetString("ServerInstanceFlushingBinaryLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to retrieve the group replication member role:.
        /// </summary>
        internal static string ServerInstanceGetGroupReplicationMemberRoleError {
            get {
                return ResourceManager.GetString("ServerInstanceGetGroupReplicationMemberRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the value of {0}..
        /// </summary>
        internal static string ServerInstanceGetVariableFail {
            get {
                return ResourceManager.GetString("ServerInstanceGetVariableFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set the variable {0}..
        /// </summary>
        internal static string ServerInstanceSetVariableFail {
            get {
                return ResourceManager.GetString("ServerInstanceSetVariableFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An authentication plugin must be specified for new users..
        /// </summary>
        internal static string ServerUserMissingAuthenticationPlugin {
            get {
                return ResourceManager.GetString("ServerUserMissingAuthenticationPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name must be given for new users..
        /// </summary>
        internal static string ServerUserMissingUserName {
            get {
                return ResourceManager.GetString("ServerUserMissingUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows authorization requires a token list..
        /// </summary>
        internal static string ServerUserMissingWindowsTokensList {
            get {
                return ResourceManager.GetString("ServerUserMissingWindowsTokensList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show {0}.
        /// </summary>
        internal static string ShowPrefixText {
            get {
                return ResourceManager.GetString("ShowPrefixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t set a value if the singleton is already instantiated..
        /// </summary>
        internal static string SingletonPropertySetError {
            get {
                return ResourceManager.GetString("SingletonPropertySetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Key Files|*.ppk|All files|*.*.
        /// </summary>
        internal static string SshPrivateKeyFilter {
            get {
                return ResourceManager.GetString("SshPrivateKeyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SSH private key file.
        /// </summary>
        internal static string SshPrivateKeyTitle {
            get {
                return ResourceManager.GetString("SshPrivateKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Enhanced Mail|*.pem|All files|*.*.
        /// </summary>
        internal static string SslCertificateFilter {
            get {
                return ResourceManager.GetString("SslCertificateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SSL Certification Authority file.
        /// </summary>
        internal static string SslCertificationAuthorityTitle {
            get {
                return ResourceManager.GetString("SslCertificationAuthorityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SSL Client Certificate file.
        /// </summary>
        internal static string SslClientCertificateTitle {
            get {
                return ResourceManager.GetString("SslClientCertificateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SSL Key file.
        /// </summary>
        internal static string SslKeyTitle {
            get {
                return ResourceManager.GetString("SslKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Exchange Format|*.pfx|All files|*.*.
        /// </summary>
        internal static string SslPfxFilter {
            get {
                return ResourceManager.GetString("SslPfxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SSL PFX Certificate file.
        /// </summary>
        internal static string SslPfxTitle {
            get {
                return ResourceManager.GetString("SslPfxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process for {0}, with ID {1}, was run successfully and exited with code {2}..
        /// </summary>
        internal static string StartedAndExitedProcessSuccessfullyText {
            get {
                return ResourceManager.GetString("StartedAndExitedProcessSuccessfullyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process for {0}, with ID {1}, has been started successfully and is running..
        /// </summary>
        internal static string StartedAndRunningProcessSuccessfullyText {
            get {
                return ResourceManager.GetString("StartedAndRunningProcessSuccessfullyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process for {0} failed to start with the following error message:
        ///{1}.
        /// </summary>
        internal static string StartedProcessErrorText {
            get {
                return ResourceManager.GetString("StartedProcessErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting process with command: {0} {1}....
        /// </summary>
        internal static string StartingProcessDetailsText {
            get {
                return ResourceManager.GetString("StartingProcessDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value is greater than end value.
        /// </summary>
        internal static string StartValueGreaterThanEndValueExceptionText {
            get {
                return ResourceManager.GetString("StartValueGreaterThanEndValueExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessText {
            get {
                return ResourceManager.GetString("SuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type parameter TEnum must be an Enum.
        /// </summary>
        internal static string TEnumNotEnumTypeException {
            get {
                return ResourceManager.GetString("TEnumNotEnumTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an indented block..
        /// </summary>
        internal static string TokenizerIndentedBlockExpectedError {
            get {
                return ResourceManager.GetString("TokenizerIndentedBlockExpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character after line continuation character..
        /// </summary>
        internal static string TokenizerUnexpectedCharAfterLineContinuatonError {
            get {
                return ResourceManager.GetString("TokenizerUnexpectedCharAfterLineContinuatonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unindent does not match any outer indentation level..
        /// </summary>
        internal static string TokenizerUnexpectedDedentError {
            get {
                return ResourceManager.GetString("TokenizerUnexpectedDedentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected indentation..
        /// </summary>
        internal static string TokenizerUnexpectedIndentError {
            get {
                return ResourceManager.GetString("TokenizerUnexpectedIndentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove connection..
        /// </summary>
        internal static string UnableToDeleteConnectionErrorDetail {
            get {
                return ResourceManager.GetString("UnableToDeleteConnectionErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting connections is not allowed while MySQL Workbench is running..
        /// </summary>
        internal static string UnableToDeleteConnectionsWhenWBRunning {
            get {
                return ResourceManager.GetString("UnableToDeleteConnectionsWhenWBRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to merge existing connections with MySQL Workbench..
        /// </summary>
        internal static string UnableToMergeConnectionsErrorDetail {
            get {
                return ResourceManager.GetString("UnableToMergeConnectionsErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} now works with the connections file used by MySQL Workbench if it is installed.
        ///
        ///{0} attempted to merge all existing connections with MySQL Workbench but is unable to do that if MySQLWorkbench is running.
        ///
        ///Please close MySQL Workbench and restart {0} to perform the merge..
        /// </summary>
        internal static string UnableToMergeConnectionsErrorMoreInfo {
            get {
                return ResourceManager.GetString("UnableToMergeConnectionsErrorMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpectedly reached end of binary stream.
        ///Error : {0}.
        /// </summary>
        internal static string UnexpectedEndOfStreamError {
            get {
                return ResourceManager.GetString("UnexpectedEndOfStreamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binary stream was unexpectedly closed.
        ///Error : {0}.
        /// </summary>
        internal static string UnexpectedStreamClosingError {
            get {
                return ResourceManager.GetString("UnexpectedStreamClosingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        internal static string UnhandledExceptionText {
            get {
                return ResourceManager.GetString("UnhandledExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown I/O error.
        ///Error : {0}.
        /// </summary>
        internal static string UnknownIOError {
            get {
                return ResourceManager.GetString("UnknownIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warnings {
            get {
                object obj = ResourceManager.GetObject("warnings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningsText {
            get {
                return ResourceManager.GetString("WarningsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQLWorkbench connections file was not found..
        /// </summary>
        internal static string WorkbenchConnectionsFileNotFoundError {
            get {
                return ResourceManager.GetString("WorkbenchConnectionsFileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find MySQL Workbench..
        /// </summary>
        internal static string WorkbenchNotInstalled {
            get {
                return ResourceManager.GetString("WorkbenchNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yes {
            get {
                object obj = ResourceManager.GetObject("yes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesButtonText {
            get {
                return ResourceManager.GetString("YesButtonText", resourceCulture);
            }
        }
    }
}
