//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySql.Data.VisualStudio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySql.Data.VisualStudio.MySqlForVisualStudioSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MVCWizardConnection {
            get {
                return ((string)(this["MVCWizardConnection"]));
            }
            set {
                this["MVCWizardConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySql.Data.VisualStudio.MySqlForVisualStudioSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WinFormsWizardConnection {
            get {
                return ((string)(this["WinFormsWizardConnection"]));
            }
            set {
                this["WinFormsWizardConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySql.Data.VisualStudio.MySqlForVisualStudioSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NewProjectDialogSelected {
            get {
                return ((string)(this["NewProjectDialogSelected"]));
            }
            set {
                this["NewProjectDialogSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySql.Data.VisualStudio.MySqlForVisualStudioSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NewProjectSavedPath {
            get {
                return ((string)(this["NewProjectSavedPath"]));
            }
            set {
                this["NewProjectSavedPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySql.Data.VisualStudio.MySqlForVisualStudioSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Visual C#")]
        public string NewProjectLanguageSelected {
            get {
                return ((string)(this["NewProjectLanguageSelected"]));
            }
            set {
                this["NewProjectLanguageSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySql.Data.VisualStudio.MySqlForVisualStudioSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CreateDirectoryForSolution {
            get {
                return ((bool)(this["CreateDirectoryForSolution"]));
            }
            set {
                this["CreateDirectoryForSolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsProviderAttribute(typeof(MySql.Data.VisualStudio.MySqlForVisualStudioSettings))]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Create new solution")]
        public string CreateNewSolution {
            get {
                return ((string)(this["CreateNewSolution"]));
            }
            set {
                this["CreateNewSolution"] = value;
            }
        }
    }
}
