//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySql.Data.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySql.Data.VisualStudio.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not complete the save operation..
        /// </summary>
        internal static string BadSaveFlags {
            get {
                return ResourceManager.GetString("BadSaveFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQL.
        /// </summary>
        internal static string DataView_MySQL {
            get {
                return ResourceManager.GetString("DataView_MySQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Editor files (*.myext)
        ///*.myext
        ///
        ///.
        /// </summary>
        internal static string EditorFormatString {
            get {
                return ResourceManager.GetString("EditorFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name cannot be null..
        /// </summary>
        internal static string NullFilename {
            get {
                return ResourceManager.GetString("NullFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has changed outside the editor. Do you wish to reload it?.
        /// </summary>
        internal static string OutsideEditorFileChange {
            get {
                return ResourceManager.GetString("OutsideEditorFileChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this selection to connect to MySQL using the .NET Framework Data Provider for MySQL..
        /// </summary>
        internal static string Provider_Description {
            get {
                return ResourceManager.GetString("Provider_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework Data Provider for MySQL.
        /// </summary>
        internal static string Provider_DisplayName {
            get {
                return ResourceManager.GetString("Provider_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySqlClient.
        /// </summary>
        internal static string Provider_ShortDisplayName {
            get {
                return ResourceManager.GetString("Provider_ShortDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error from the source control provider..
        /// </summary>
        internal static string SCCError {
            get {
                return ResourceManager.GetString("SCCError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions.
        /// </summary>
        internal static string SFunc_DisplayName {
            get {
                return ResourceManager.GetString("SFunc_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Procedures.
        /// </summary>
        internal static string SProc_DisplayName {
            get {
                return ResourceManager.GetString("SProc_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string Tables_DisplayName {
            get {
                return ResourceManager.GetString("Tables_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tool Window.
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown format..
        /// </summary>
        internal static string UnknownFileFormat {
            get {
                return ResourceManager.GetString("UnknownFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string Views_DisplayName {
            get {
                return ResourceManager.GetString("Views_DisplayName", resourceCulture);
            }
        }
    }
}
