//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySql.VisualStudio.CustomAction.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySql.VisualStudio.CustomAction.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error found in the ActivityLog. Warning message will be displayed for instance: 15.0_{0}..
        /// </summary>
        internal static string ActivityLogAccessDeniedError {
            get {
                return ResourceManager.GetString("ActivityLogAccessDeniedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} assembly was found at {1}..
        /// </summary>
        internal static string AssemblyFoundAt {
            get {
                return ResourceManager.GetString("AssemblyFoundAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed existing binding redirect entries..
        /// </summary>
        internal static string BindingRedirectEntriesRemoved {
            get {
                return ResourceManager.GetString("BindingRedirectEntriesRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when calling the method {0} {1}..
        /// </summary>
        internal static string CallingMethodError {
            get {
                return ResourceManager.GetString("CallingMethodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error found when checking if Connector/NET is installed.
        /// </summary>
        internal static string ConnectorNETGeneralError {
            get {
                return ResourceManager.GetString("ConnectorNETGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created registry key. keyPath = &apos;{0}&apos;. keyName=&apos;{1}&apos;..
        /// </summary>
        internal static string CreatedRegistryKey {
            get {
                return ResourceManager.GetString("CreatedRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating registry key. keyPath = &apos;{0}&apos;. keyName=&apos;{1}&apos;..
        /// </summary>
        internal static string CreatingRegistryKey {
            get {
                return ResourceManager.GetString("CreatingRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted registry key. keyPath = &apos;{0}&apos;. keyName=&apos;{1}&apos;..
        /// </summary>
        internal static string DeletedRegistryKey {
            get {
                return ResourceManager.GetString("DeletedRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting registry key. keyPath = &apos;{0}&apos;. keyName=&apos;{1}&apos;..
        /// </summary>
        internal static string DeletingRegistryKey {
            get {
                return ResourceManager.GetString("DeletingRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing &apos;{0}&apos; custom action..
        /// </summary>
        internal static string ExecutingCustomAction {
            get {
                return ResourceManager.GetString("ExecutingCustomAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions file created for {0}..
        /// </summary>
        internal static string ExtensionsFileCreated {
            get {
                return ResourceManager.GetString("ExtensionsFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted extensions file {0}_EXTENSIONSFILE_CREATED..
        /// </summary>
        internal static string ExtensionsFileDeleted {
            get {
                return ResourceManager.GetString("ExtensionsFileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing &apos;{0}&apos;. {1}. {2}..
        /// </summary>
        internal static string FailedToExecuteCustomAction {
            get {
                return ResourceManager.GetString("FailedToExecuteCustomAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the {0} assembly..
        /// </summary>
        internal static string FailedToLoadAssembly {
            get {
                return ResourceManager.GetString("FailedToLoadAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse the OldVersion entry 0} for {1}.&quot;.
        /// </summary>
        internal static string FailedToParseOldVersionEntry {
            get {
                return ResourceManager.GetString("FailedToParseOldVersionEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse parameter &apos;VSVersion&apos; to a valid &apos;SupportedVisualStudioVersions&apos; value..
        /// </summary>
        internal static string FailedToParseVSVersion {
            get {
                return ResourceManager.GetString("FailedToParseVSVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was raised when attempting to read the ActivityLog: {0}..
        /// </summary>
        internal static string FailedToReadActivityLog {
            get {
                return ResourceManager.GetString("FailedToReadActivityLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the PKGDEF file for {0} at: {1}..
        /// </summary>
        internal static string FailedToReadThePkgdefFile {
            get {
                return ResourceManager.GetString("FailedToReadThePkgdefFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: The \&quot;devenv /updateconfiguration\&quot; command may have failed to execute succesfully preventing Visual Studio 2017 from registering/unregistering MySQL for Visual Studio. If affected, run the command manually using \&quot;Developer Command Prompt for VS\&quot;. For additional details, see the product documentation..
        /// </summary>
        internal static string FailedToRefreshExtensions {
            get {
                return ResourceManager.GetString("FailedToRefreshExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to write to the PKGDEF file. Validate that the application is running with administrator privileges..
        /// </summary>
        internal static string FailedToWriteToPkgdefFile {
            get {
                return ResourceManager.GetString("FailedToWriteToPkgdefFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature {0} is not supported..
        /// </summary>
        internal static string FeatureNotSupported {
            get {
                return ResourceManager.GetString("FeatureNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OldVersion entry was expected to reference the internal version of MySql.Data library ({0})..
        /// </summary>
        internal static string IncorrectReferenceInOldVersionEntry {
            get {
                return ResourceManager.GetString("IncorrectReferenceInOldVersionEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version of Connector/NET and the MySql.Data library is: {0}.
        /// </summary>
        internal static string InstalledMySqlDataVersion {
            get {
                return ResourceManager.GetString("InstalledMySqlDataVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySql.Data library included in MySQL for Visual Studio is: {0}.
        /// </summary>
        internal static string InternalMySqlDataVersion {
            get {
                return ResourceManager.GetString("InternalMySqlDataVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoking method on custom installer..
        /// </summary>
        internal static string InvokingMethodOnCustomInstaller {
            get {
                return ResourceManager.GetString("InvokingMethodOnCustomInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method information was null..
        /// </summary>
        internal static string MethodNullInformation {
            get {
                return ResourceManager.GetString("MethodNullInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MySql.Data library was not found..
        /// </summary>
        internal static string MySqlDataNotFound {
            get {
                return ResourceManager.GetString("MySqlDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MySql.Data library included in the installed version of Connector/NET matches the one included with MySQL for Visual Studio. No further action is needed..
        /// </summary>
        internal static string MySqlDataVersionsMatch {
            get {
                return ResourceManager.GetString("MySqlDataVersionsMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the PKGDEF file is not required. Both versions of MySql.Data libraries match..
        /// </summary>
        internal static string MySqlDataVersionsMatchNoUpdateRequired {
            get {
                return ResourceManager.GetString("MySqlDataVersionsMatchNoUpdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the PKGDEF file is not required. MySQL for Visual Studio is not installed..
        /// </summary>
        internal static string MySQLForVisualStudioNotInstalledNoUpdateRequired {
            get {
                return ResourceManager.GetString("MySQLForVisualStudioNotInstalledNoUpdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PKGDEF file has been updated..
        /// </summary>
        internal static string PkgdefFileUpdated {
            get {
                return ResourceManager.GetString("PkgdefFileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update of the PKGDEF file failed for feature {0} with error: {1}..
        /// </summary>
        internal static string PkgdefFileUpdateFailedForFeature {
            get {
                return ResourceManager.GetString("PkgdefFileUpdateFailedForFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} installation path: {1}..
        /// </summary>
        internal static string ProductInstallationPath {
            get {
                return ResourceManager.GetString("ProductInstallationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not installed..
        /// </summary>
        internal static string ProductNotInstalled {
            get {
                return ResourceManager.GetString("ProductNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set session value. {0}={1}..
        /// </summary>
        internal static string SetSessionVariableValue {
            get {
                return ResourceManager.GetString("SetSessionVariableValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to update the PKGDEF file for feature {0}..
        /// </summary>
        internal static string UpdatingPkgdefFileForFeature {
            get {
                return ResourceManager.GetString("UpdatingPkgdefFileForFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine installation path of Visual Studio..
        /// </summary>
        internal static string VisualStudioInstallationPathNotFound {
            get {
                return ResourceManager.GetString("VisualStudioInstallationPathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of Visual Studio was not selected for installation by the user. Updating the PKGDEF file is not required..
        /// </summary>
        internal static string VisualStudioVersionNotSelected {
            get {
                return ResourceManager.GetString("VisualStudioVersionNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of Visual Studio is not supported..
        /// </summary>
        internal static string VisualStudioVersionNotSupported {
            get {
                return ResourceManager.GetString("VisualStudioVersionNotSupported", resourceCulture);
            }
        }
    }
}
